# Generated by Django 5.2.7 on 2025-10-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_timestamp_alter_room_name_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='channel_type',
            field=models.CharField(choices=[('text', 'Metin'), ('voice', 'Sesli')], default='text', max_length=5),
        ),
    ]
