"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# --- 1. ALLOWED_HOSTS Kontrolü ---
# Güvenlik açısından tavsiye edilmez ama geliştirme için en hızlı çözümdür.
# Django'ya tüm gelen isteklere yanıt vermesini söyler.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost','*', 'pseudostudiously-reflexional-clara.ngrok-free.dev']

# --- 2. CORS Ayarları (Gerekirse) ---
# WebSocket için bu zorunlu değildir, ancak React'in diğer HTTP işlemleri için önemlidir.
# (Eğer frontend'e HTTP/API işlemleri eklersek diye bırakıyoruz, şimdilik etkisi az)
CORS_ALLOW_ALL_ORIGINS = True # <-- En basit çözüm
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CORS_ALLOWED_ORIGINS = [
    "https://pawscord-frontend.vercel.app",'pseudostudiously-reflexional-clara.ngrok-free.dev',
    # Geliştirme için localhost'u da listede tutalım
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a_n55upuxdrj-jqri-r0do+o2as=y3um_=364u0-2-9bs25&@v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','*',"pseudostudiously-reflexional-clara.ngrok-free.dev"] # <-- Bu da çözülmüş olmalıydı, tekrar kontrol edin!
# =========================================================
# NGROK/HTTPS/GÜVENLİK AYARLARI (GEREKLİDİR)
# =========================================================

# 1. ALLOWED_HOSTS (Bu zaten yapılmış olmalı, kontrol edin!)
ALLOWED_HOSTS = ['127.0.0.1', 'localhost','*', 'pseudostudiously-reflexional-clara.ngrok-free.dev']


# 2. CSRF GÜVENLİK İZNİ
# Ngrok üzerinden gelen HTTPS bağlantıları için alan adını güvenilir say
CSRF_TRUSTED_ORIGINS = ['https://pawscord-frontend.vercel.app','https://pseudostudiously-reflexional-clara.ngrok-free.dev']

# 3. NGROK HTTPS DÜZELTMESİ
# Django'ya, Ngrok'tan gelen HTTPS başlıklarını kabul etmesini söyler.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Geliştirme kolaylığı için Django'nun bu hatalarda takılmasını engeller:
CORS_ALLOW_ALL_ORIGINS = True # (Corsheaders kuruluysa)
# Application definition
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Kendi uygulamalarımız ve Paketler (Sadece birer kez listelenmeli)
    'chat',  # Kendi Uygulamamız
    'channels',  # Django Channels
    'corsheaders',  # CORS yönetimi
    'rest_framework',  # Django REST Framework

    # Tüm tekrarlar (chat, channels, corsheaders) buradan çıkarılmıştır.
]

MIDDLEWARE = [
    # CORS ORTA KATMAN YAZILIMI, GÜVENLİK İŞLEMLERİNDEN ÖNCE GELMELİDİR!
    'corsheaders.middleware.CorsMiddleware', # <-- EN ÜSTE YAKIN OLMALI!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

import os 
# from pathlib import Path <-- Eğer varsa, bu da kalabilir
# BASE_DIR = Path(__file__).resolve().parent.parent 


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        # KRİTİK KONTROL: Bu yol, index.html dosyasını İÇEREN klasör olmalıdır.
        'DIRS': [os.path.join(BASE_DIR, 'frontend/build')], # <-- BU BUILD OLMALI!
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # debug'ı eklemeyi unutmayın
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
ASGI_APPLICATION = 'core.asgi.application'

# Kanal Katmanı (Basit bir in-memory ayarı kullanıyoruz)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/' 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

# KRİTİK KONTROL: Statik dosyaların aranacağı ek dizinler
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/build/static'), # <-- BURASI KESİNLİKLE DOĞRU OLMALI
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
